main/urls.py
from django.urls import path
from .views import home, search, detail, RecipeCreate, comentar

urlpatterns = [
    path("", home, name="home"),
    path('cadastrar/', RecipeCreate.as_view(), name='cadastros'),
    path("search", search, name="search"),
    path("<slug>", detail, name="detail"),
    path('comentar/', comentar.as_view(), name='comentar'),
]

project/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
  
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    # Local
    path("", include("pages.urls", namespace="pages")),
    
]

main/models.py
from django.db import models
from autoslug import AutoSlugField
from django.shortcuts import reverse
from django.conf import settings

class Cidade(models.Model):
    title = models.CharField(max_length=200)

    slug = AutoSlugField(populate_from="title")
    def __str__(self):
        return self.title

class Topic(models.Model):
    title = models.CharField(max_length=200)

    slug = AutoSlugField(populate_from="title")
    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from="title")
    image = models.CharField(max_length=400)
    descricao = models.TextField()
    endereco = models.TextField()
    servicos = models.TextField()
    detalhes = models.CharField(max_length=5)
    desde = models.CharField(max_length=5)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("detail", kwargs={
            "slug":self.slug,
        })
class Comentario(models.Model):
    session_client = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    conteudo = models.TextField(max_length=420, default='')
    Local = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    def __str__(self):
        return self.conteudo

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Recipe
from .models import Comentario
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required



class RecipeCreate(CreateView):
    
    model = Recipe
    fields = ['title','image','descricao','endereco','servicos','detalhes','desde','topic','cidade']
    template_name = 'Base2.html'
    success_url = reverse_lazy('home')

def home(request):
    total_recipes = Recipe.objects.all().count()
    recipes = Recipe.objects.all()
    inter2=[]
    for recipe in recipes:
        inter2.append(recipe)
    context = {
        "title":"Homepage",
        "total_recipes":total_recipes,
        "recipes":recipes,
        "inter2":inter2,
    }  
        
    return render(request, "home.html", context)

class comentar(CreateView):
    
    model = Comentario
    fields = ['conteudo','Local','session_client']
    template_name = 'base2.html'
    success_url = reverse_lazy('home')

def search(request):
    recipes = Recipe.objects.all()
    inter = []
    results1=[]
    results2=[]
    results3=[]
    results4=[]
    results5=[]
    results6=[]
    results7=[]
    results8=[]
    results9=[]
    results10=[]
    results=[]
    b = False

    if "search" in request.GET:
        query = request.GET.get("search")
        queryset = recipes.filter(Q(title__icontains=query))
        results = recipes.filter(Q(title__icontains=query))
        topic = ''
        cidade =''
    
    if request.GET.get("Itacaré"):
        results1 = queryset.filter(Q(cidade__title__icontains="Itacaré"))
        cidade = "Itacaré"
        b = True
    if request.GET.get("Ilhéus"):
        results2 = queryset.filter(Q(cidade__title__icontains="Ilhéus"))
        cidade="Ilhéus"
        b = True    
    if request.GET.get("Bares"):
        results3 = queryset.filter(Q(topic__title__icontains="Bares"))
        topic = "Bares"
        b = True  
    if request.GET.get("Restaurantes"):
        results4 = queryset.filter(Q(topic__title__icontains="Restaurantes"))
        topic="Restaurantes"
        b = True 
    if request.GET.get("Eventos"):
        results5 = queryset.filter(Q(topic__title__icontains="Eventos"))
        topic="Eventos"
        b = True 
    if request.GET.get("Hospedagens"):
        results6 = queryset.filter(Q(topic__title__icontains="Hospedagens"))
        topic="Hospedagens"
        b = True 
    if request.GET.get("Passeios Turísticos"):
        results7 = queryset.filter(Q(topic__title__icontains="Passeios Turísticos"))
        topic="Passeios Turísticos"
        b = True 
    if request.GET.get("Praças"):
        results8 = queryset.filter(Q(topic__title__icontains="Praças"))
        topic="Praças"
        b = True 
    if request.GET.get("Feiras"):
        results9 = queryset.filter(Q(topic__title__icontains="Feiras"))
        topic="Feiras"
        b = True 
    if request.GET.get("Comércios"):
        results10 = queryset.filter(Q(topic__title__icontains="Comércios"))
        topic="Comércios"
        b = True 

    
    
    a = False
    for x in recipes:
        for y in results1:
            if x == y:
                if x not in inter:
                    inter.append(x)
                    a = True
        for y in results2:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
        for y in results3:
            if x == y:
                if x not in inter:
                    inter.append(x)
                    a = True
        for y in results4:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
        for y in results5:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
        for y in results6:
            if x == y:
                if x not in inter:
                    inter.append(x)
                    a = True
        for y in results7:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
        for y in results8:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
        for y in results9:
            if x == y:
                if x not in inter:
                    inter.append(x)
                    a = True
        for y in results10:
            if x == y:
               if x not in inter:
                    inter.append(x)
                    a = True
          
    if a == False and b == False:
        inter = results
                
    
    #paginate results
    paginator = Paginator(results, 3)
    page = request.GET.get("page")
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        "cidade":cidade,
        "topic":topic,
        "page":page,
        "results2":results2,
        "results3":results3,
        "results4":results4,
        "results5":results5,
        "results6":results6,
        "results7":results7,
        "results8":results8,
        "results9":results9,
        "results10":results10,
        "query":query,
        "results":results,
        "results1":results1,
        "inter":inter,
   
       
    }
    return render(request, "search.html", context)

def detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    context = {
        "recipe":recipe,
    }
    return render(request, "detail.html", context)




main/templates/base2.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Novo App</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% if user.is_authenticated %}
        <h2>Cadastrar</h2>
        <form class="form-wrap mt-4" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Cadastrar</button>
        </form>
        {% else %}
        <h2>Faça login para cadastrar seu local!</h2>
        {% endif %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

main/templates/detail.html
<!DOCTYPE html>
<html lang="en">

   {% include 'head.html' %}
      <style>
         li {
         font-size: 0.95rem;
         line-height: 1.7rem;
         }
         .circle{
         background-color: #e6ffe6;
         border-radius: 50px;
         padding: 20px;
         }
         .circle:hover{
         background-color:#99ff99;
         }
         .rectangle{
         background-color: #ffb3b3;
         padding: 20px;
         }
         .rectangle:hover{
         background-color:#ffe6e6;
         }
         html,
       body,
       header,
       .jarallax {
       height: 1000px;
       min-height: 800px;
       }
       .logo {
            margin-top: -40px;
            display: inline-block;
      }
  .a {
     color: aliceblue;
  }
  .nav-menu {
  position: absolute;
  z-index: 1;
  top: 0;
  right: 0;
  left: 0;
  margin: 0 auto;
  background: #252a33; }
  a {
 
  color:aliceblue }
  h6 {
  font-size: 21px;
  font-weight: 400;
  color:black; }
  .slider {
  background: url(../images/slider.jpg) no-repeat;
  background-size: cover;
  min-height: 800px; }
    </style>
 
   
 <body>
   <div class="a">
 <!--============================= HEADER =============================-->
 <div class="nav-menu">
 
                       <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
                           <div class="container">
                               <a class="navbar-brand" href="{% url 'pages:home' %}">Novo App</a>
                               <ul class="navbar-nav">
                                   {% if user.is_authenticated %}
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                                   </li>
                                   {% else %}
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                                   </li>
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                                   </li>
                                   {% endif %}
                               </ul>
                           </div>
                       </nav>
                
                
                                   
                               
                             
                             </ul>
                         </div>
                     </nav>
                 </div>
             </div>
         </div>
     </div>
 </div>
      <!-- /main nav -->
</div>
</header>
<body>
         
        
        
<section>
   <div class="" style="max-height:600px;">
      <img src="{{recipe.image}}" style="width: 100%">
   </div>
   
</section>
       
      <!-- Main Navigation -->
      <!-- Main Layout -->
      <main>
         
         <div class="container-fluid mt-5 mt-md-0 mb-5">
            <!-- Grid row -->
            <div class="row" style="margin-top: -100px;">
               <!-- Grid column -->
               <div class="col-md-12 px-lg-5">
                  <!-- Card -->
                  <div class="card pb-5 mx-md-3">
                     <h6>#{{recipe.topic.title}}</h6>
                     <section class="reserve-block">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <h5>{{recipe.title}}</h5>
                                    
                                   
                                </div>
                                <div class="col-md-6">
                                    <div class="reserve-seat-block">
                                      
                                       
                                        <div class="review-btn">
                                            <a href="#" class="btn btn-outline-danger">Fazer Comentário</a>
                                            
                                        </div>
                                        <div class="reserve-btn">
                                            <div class="featured-btn-wrap">
                                                <a href="#" class="btn btn-danger">Entrar em Contato</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section class="light-bg booking-details_wrap">
                     <div class="container">
                      

                    
   
                              <!-- Grid column -->
                              <div class="col-md-12 col-xl-12">
                                 <!-- Grid row -->
                                 <!---------------------------------------------------------------------------------------------------->
                                 <h6>Descrição</h6>
                                 <p> {{recipe.descricao|safe}}</p>
                                 
                                 <div class="row">
                                    <div class="col-md-6 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                                       
                                       <div class="jumbotron" style="background-color: #f5f5f0">
                                          
                                          <span>Endereço:</span>
                                    <div class="address">
                                       <span class="icon-location-pin"></span>
                                       
                                       <p>{{recipe.endereco|safe}}</p>
                                   </div>
                                        
                                       </div>
                                    </div>
                                    <div class="col-md-6 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                                       <div class="jumbotron" style="background-color: #f5f5f0">
                                          <span>Serviços:</span>
                                          <p> {{recipe.servicos|safe}}</p>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                   
              
                                 <!---------------------------------------------------------------------------------------------------->
                                 <!-- Grid row -->
                                 <div class="row my-5">
                                    <!-- Grid column -->
                                    <div class="col-md-12 text-center">
                                       <h4 class="text-center font-weight-bold dark-grey-text mt-3 mb-3">
                                          <strong>Share this post: </strong>
                                       </h4>
                                       <button type="button" class="btn btn-fb btn-sm">
                                       <i class="fab fa-facebook-f left"></i> Facebook</button>
                                       <!-- Twitter -->
                                       <button type="button" class="btn btn-tw btn-sm">
                                       <i class="fab fa-twitter left"></i> Twitter</button>
                                       <!-- Google + -->
                                       <button type="button" class="btn btn-gplus btn-sm">
                                       <i class="fab fa-google-plus-g left"></i> Google +</button>
                                    </div>
                                    <!-- Grid column -->
                                 </div>
                                 <!-- Grid row -->
                                 <hr class="mt-5">
                                 <!-- Section: Leave a reply (Not Logged In User) -->
                              </div>
                              <!-- Grid column -->
                           </div>
                           <!-- Grid row -->
                        </div>
                     </div>
                  </div>
                  <!-- Card -->
               </div>
               <!-- Grid column -->
            </div>
            <!-- Grid row -->
            <div class="text-center mt-5">
               <a href="{% url 'home' %}">Back Home</a>
            </div>
         </div>
      </main>
      <!-- Main Layout -->
      
      <!-- Footer -->
      <footer class="main-block dark-bg">
         <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="copyright">
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                         <p>Copyright &copy; 2018 Listing. All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">LRL</a></p>
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                         <ul>
                             <li><a href="#"><span class="ti-facebook"></span></a></li>
                             <li><a href="#"><span class="ti-twitter-alt"></span></a></li>
                             <li><a href="#"><span class="ti-instagram"></span></a></li>
                         </ul>
                     </div>
                 </div>
             </div>
         </div>
     </footer>
      </body>
      </html>
      <!-- SCRIPTS -->
      {% include 'scripts.html' %}
      
      <script>
         new WOW().init();
         
         $(function () {
           var selectedClass = "";
           $(".filter").click(function () {
             selectedClass = $(this).attr("data-rel");
             $("#gallery").fadeTo(100, 0.1);
             $("#gallery div").not("." + selectedClass).fadeOut().removeClass('animation');
             setTimeout(function () {
               $("." + selectedClass).fadeIn().addClass('animation');
               $("#gallery").fadeTo(300, 1);
             }, 300);
           });
         });
      </script>

main/templates/scripts.html
    {% load static %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/mdb.min.js' %}"></script>

main/templates/search.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}

   {% include 'head.html' %}
    <style>
       html,
       body,
       header,
       .jarallax {
       height: 1000px;
       min-height: 800px;
       }
       .logo {
            margin-top: -40px;
            display: inline-block;
      }
  .a {
     color: aliceblue;
  }
  .nav-menu {
  position: absolute;
  z-index: 1;
  top: 0;
  right: 0;
  left: 0;
  margin: 0 auto;
  background: #252a33; }
  a {
 
  color:aliceblue }
  h6 {
  font-size: 21px;
  font-weight: 400;
  color:black; }
  .slider {
  background: url(../images/slider.jpg) no-repeat;
  background-size: cover;
  min-height: 800px; }
    </style>
  <body>
   <div class="a">
 <!--============================= HEADER =============================-->
 <div class="nav-menu">
 
                       <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
                           <div class="container">
                               <a class="navbar-brand" href="{% url 'pages:home' %}">Novo App</a>
                               <ul class="navbar-nav">
                                   {% if user.is_authenticated %}
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                                   </li>
                                   {% else %}
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                                   </li>
                                   <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                                   </li>
                                   {% endif %}
                               </ul>
                           </div>
                       </nav>
                
                
                                   
                               
                             
                             </ul>
                         </div>
                     </nav>
                 </div>
             </div>
         </div>
     </div>
 </div>
      <!-- /main nav -->
</div>
</header>
&nbsp;
<body>
   <body style="min-height:800px;background-image: url(https://cdn.pixabay.com/photo/2016/02/05/15/34/pasta-1181189__340.jpg); background-repeat: no-repeat; background-size: cover; background-position: center center;">
      <div class="mask rgba-gradient7">
         <div class="container h-100 d-flex justify-content-center align-items-center">
            <!-- Grid row -->
            <div class="row  pt-5 mt-3">
               <!-- Grid column -->
               <div class="col-md-12">
                  <div class="card">
                     <div class="card-body">
                        
                        <h5>{{query}} Resultados Encontrados.</h5>
                     </div>
                  </div>
               </div>
               <!-- Grid column -->
            </div>
            <!-- Grid row -->
         </div>
      </div>
      
      <div class="jumbotron">
         
         <h6>#{{topic.title}}</h6>
         <h6>#{{cidade.title}}</h6>

         <div class="container mt-5">
            <!--Section: Content-->
            <section class="">
               
               <!-- Grid row -->
               <div class="row">

               
                 
                     {% for recipe in inter %}
                  <!-- Grid column -->
                  <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
                     <!-- Card -->
                     <div class="card hoverable">
                        <!-- Card image -->
                        <img class="card-img-top" src="{{recipe.image}}" alt="Card image cap">
                        <!-- Card content -->
                        <div class="card-body">
                           <!-- Title -->
                           <a href="{{recipe.get_url}}" class="black-text">{{recipe.title}}</a>
                           <!-- Text -->
                           <p class="card-title text-muted font-small mt-3 mb-2">{{recipe.description|safe|slice:":150"}}</p>
                           <a type="button" class="btn btn-flat text-primary p-0 mx-0" href="{{recipe.get_url}}">Read more<i class="fa fa-angle-right ml-2"></i></a>
                        </div>
                     </div>
                     <!-- Card -->
                  </div>
                  {% endfor %}
                


                  


              
                 
               </div>
               <!-- Grid row -->


               <!--##############################Pagination################################-->
 
               <!-- Pagination -->
               <nav class="my-4 flex-center">
                  <ul class="list-unstyled pagination pagination-circle pg-blue mb-0">
                     
                     <!-- First -->
                     {% if page == "1" %}
                     <li class="page-item disabled clearfix d-none d-md-block">
                        <a class="page-link" href="#">First</a>
                     </li>
                     {% else %}
                     <li class="page-item clearfix d-none d-md-block">
                        <a class="page-link" href="?{{topic}}=on&search={{query}}&page=1">First</a>
                     </li>
                     {% endif %}
               
                     <!-- Arrow left -->
                     {% if results.has_previous %}
                     <li class="page-item">
                        <a class="page-link" href="?{{topic}}=on&search={{query}}&page={{results.previous_page_number}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                        </a>
                     </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                        </a>
                     </li>
                     {% endif %}
                  
                     <!-- Numbers -->
                     {% for number in results.paginator.page_range %}
                     <li class="page-item">
                        <a class="page-link" href="?{{topic}}=on&search={{query}}&page={{number}}">{{number}}</a>
                     </li>
                     {% endfor %}
                  
      
                     <!-- Arrow right -->
                     {% if results.has_next %}
                     <li class="page-item">
                        <a class="page-link" href="?{{topic}}=on&search={{query}}&page={{results.next_page_number}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                        </a>
                     </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                        </a>
                     </li>
                     {% endif %}

                     <!-- Last -->
                     {% if page != results.paginator.num_pages %}
                     <li class="page-item clearfix d-none d-md-block">
                        <a class="page-link" href="?{{topic}}=on&search={{query}}&page={{results.paginator.num_pages}}">Last</a>
                     </li>
                     {% else %}
                     <li class="page-item clearfix d-none d-md-block disabled">
                        <a class="page-link" href="#">Last</a>
                     </li>
                     {% endif %}
                  </ul>
               </nav>
               <!-- Pagination -->
               
               <div class="text-center mt-5">
                  <a class="btn btn-outline top-btn" href="/">Back Home</a>
               </div>
            </section>
            
            <!--Section: Content-->
         </div>
      </div>
      <footer class="main-block dark-bg">
         <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="copyright">
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                         <p>Copyright &copy; 2018 Listing. All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">LRL</a></p>
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                         <ul>
                             <li><a href="#"><span class="ti-facebook"></span></a></li>
                             <li><a href="#"><span class="ti-twitter-alt"></span></a></li>
                             <li><a href="#"><span class="ti-instagram"></span></a></li>
                         </ul>
                     </div>
                 </div>
             </div>
         </div>
     </footer>
      <!-- Main Navigation -->
      {% include 'scripts.html' %}
   </body>
</html>